# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-02 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nextdoor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='pic',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='pictures/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alert',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='business',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='hood_pic',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
