# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-04 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextdoor', '0002_auto_20210202_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='occupants',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
