# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-06 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextdoor', '0004_auto_20210204_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='profiles/default.jpeg', upload_to='profiles/'),
        ),
    ]
