# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-06 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextdoor', '0005_auto_20210206_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='profiles/default.png', upload_to='profiles/'),
        ),
    ]
