# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-06 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextdoor', '0007_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(default='add your general location', max_length=250),
        ),
    ]
